In [1]:
from dotenv import load_dotenv
import os

load_dotenv()

API_KEY = os.getenv("FMP_API_KEY")

print(API_KEY[:5] + "...")

v2Gxr...

In [4]:
from dotenv import load_dotenv
import os
import requests
import pandas as pd

load_dotenv()

API_KEY = os.getenv("FMP_API_KEY")

ticker = "AAPL"

url = "https://financialmodelingprep.com/stable/historical-price-eod/full"

params = {
    "symbol": ticker,
    "apikey": API_KEY
}

response = requests.get(url, params=params)

print(response.status_code)
print(response.url.replace(API_KEY, "API_KEY_HIDDEN"))

data = response.json()
data

200
https://financialmodelingprep.com/stable/historical-price-eod/full?symbol=AAPL&apikey=API_KEY_HIDDEN

[{'symbol': 'AAPL',
  'date': '2026-05-22',
  'open': 306.12,
  'high': 311.4,
  'low': 305.84,
  'close': 308.82,
  'volume': 43670223,
  'change': 2.7,
  'changePercent': 0.88201,
  'vwap': 308.045},
 {'symbol': 'AAPL',
  'date': '2026-05-21',
  'open': 301.06,
  'high': 305.54,
  'low': 300.4,
  'close': 304.99,
  'volume': 42965126,
  'change': 3.94,
  'changePercent': 1.31,
  'vwap': 302.9975},
 {'symbol': 'AAPL',
  'date': '2026-05-20',
  'open': 298.18,
  'high': 302.8,
  'low': 298.08,
  'close': 302.25,
  'volume': 38229843,
  'change': 4.07,
  'changePercent': 1.36,
  'vwap': 300.3275},
 {'symbol': 'AAPL',
  'date': '2026-05-19',
  'open': 296.97,
  'high': 300.51,
  'low': 296.35,
  'close': 298.97,
  'volume': 42243600,
  'change': 2,
  'changePercent': 0.67347,
  'vwap': 298.2},
 {'symbol': 'AAPL',
  'date': '2026-05-18',
  'open': 300.24,
  'high': 300.66,
  'low': 294.91,
  'close': 297.84,
  'volume': 34483000,
  'change': -2.4,
  'changePercent': -0.79936,
  'vwap': 298.4125},
 {'symbol': 'AAPL',
  'date': '2026-05-15',
  'open': 297.9,
  'high': 303.2,
  'low': 296.52,
  'close': 300.23,
  'volume': 54862836,
  'change': 2.33,
  'changePercent': 0.78214,
  'vwap': 299.4625},
 {'symbol': 'AAPL',
  'date': '2026-05-14',
  'open': 299.82,
  'high': 300.45,
  'low': 295.38,
  'close': 298.21,
  'volume': 35324922,
  'change': -1.61,
  'changePercent': -0.53699,
  'vwap': 298.465},
 {'symbol': 'AAPL',
  'date': '2026-05-13',
  'open': 293.5,
  'high': 300.92,
  'low': 293.5,
  'close': 298.87,
  'volume': 52684300,
  'change': 5.37,
  'changePercent': 1.83,
  'vwap': 296.6975},
 {'symbol': 'AAPL',
  'date': '2026-05-12',
  'open': 292.56,
  'high': 295.27,
  'low': 292.56,
  'close': 294.8,
  'volume': 45748129,
  'change': 2.24,
  'changePercent': 0.76565,
  'vwap': 293.7975},
 {'symbol': 'AAPL',
  'date': '2026-05-11',
  'open': 291.98,
  'high': 293.88,
  'low': 290.23,
  'close': 292.68,
  'volume': 42247300,
  'change': 0.701,
  'changePercent': 0.23974,
  'vwap': 292.1925},
 {'symbol': 'AAPL',
  'date': '2026-05-08',
  'open': 290.01,
  'high': 294.76,
  'low': 290,
  'close': 293.32,
  'volume': 52692800,
  'change': 3.31,
  'changePercent': 1.14,
  'vwap': 292.0225},
 {'symbol': 'AAPL',
  'date': '2026-05-07',
  'open': 289.27,
  'high': 292.13,
  'low': 285.78,
  'close': 287.44,
  'volume': 45224300,
  'change': -1.83,
  'changePercent': -0.63263,
  'vwap': 288.655},
 {'symbol': 'AAPL',
  'date': '2026-05-06',
  'open': 281.92,
  'high': 288.03,
  'low': 281.07,
  'close': 287.51,
  'volume': 58336100,
  'change': 5.59,
  'changePercent': 1.98,
  'vwap': 284.6325},
 {'symbol': 'AAPL',
  'date': '2026-05-05',
  'open': 276.93,
  'high': 284.57,
  'low': 276.5,
  'close': 284.18,
  'volume': 49311712,
  'change': 7.25,
  'changePercent': 2.62,
  'vwap': 280.545},
 {'symbol': 'AAPL',
  'date': '2026-05-04',
  'open': 279.65,
  'high': 280.63,
  'low': 274.86,
  'close': 276.83,
  'volume': 46668401,
  'change': -2.82,
  'changePercent': -1.01,
  'vwap': 277.9925},
 {'symbol': 'AAPL',
  'date': '2026-05-01',
  'open': 278.86,
  'high': 287.22,
  'low': 278.37,
  'close': 280.14,
  'volume': 79915442,
  'change': 1.28,
  'changePercent': 0.45901,
  'vwap': 281.1475},
 {'symbol': 'AAPL',
  'date': '2026-04-30',
  'open': 270.5,
  'high': 276,
  'low': 268.14,
  'close': 271.35,
  'volume': 91848230,
  'change': 0.85,
  'changePercent': 0.31423,
  'vwap': 271.4975},
 {'symbol': 'AAPL',
  'date': '2026-04-29',
  'open': 267.55,
  'high': 271.04,
  'low': 267.04,
  'close': 270.22,
  'volume': 30047900,
  'change': 2.67,
  'changePercent': 0.99794,
  'vwap': 268.9625},
 {'symbol': 'AAPL',
  'date': '2026-04-28',
  'open': 272.33,
  'high': 273.23,
  'low': 268.66,
  'close': 270.71,
  'volume': 40018940,
  'change': -1.62,
  'changePercent': -0.59487,
  'vwap': 271.2325},
 {'symbol': 'AAPL',
  'date': '2026-04-27',
  'open': 266.09,
  'high': 268.36,
  'low': 265.07,
  'close': 267.61,
  'volume': 41466800,
  'change': 1.52,
  'changePercent': 0.57124,
  'vwap': 266.7825},
 {'symbol': 'AAPL',
  'date': '2026-04-24',
  'open': 272.76,
  'high': 273.06,
  'low': 269.65,
  'close': 271.06,
  'volume': 38157110,
  'change': -1.69,
  'changePercent': -0.62326,
  'vwap': 271.6325},
 {'symbol': 'AAPL',
  'date': '2026-04-23',
  'open': 275.05,
  'high': 275.77,
  'low': 271.65,
  'close': 273.43,
  'volume': 33399639,
  'change': -1.62,
  'changePercent': -0.58898,
  'vwap': 273.975},
 {'symbol': 'AAPL',
  'date': '2026-04-22',
  'open': 267.82,
  'high': 273.74,
  'low': 266.87,
  'close': 273.17,
  'volume': 43249204,
  'change': 5.35,
  'changePercent': 2,
  'vwap': 270.4},
 {'symbol': 'AAPL',
  'date': '2026-04-21',
  'open': 271.5,
  'high': 272.8,
  'low': 265.4,
  'close': 266.17,
  'volume': 50209800,
  'change': -5.33,
  'changePercent': -1.96,
  'vwap': 268.9675},
 {'symbol': 'AAPL',
  'date': '2026-04-20',
  'open': 270.33,
  'high': 274.27,
  'low': 270.29,
  'close': 273.05,
  'volume': 36590200,
  'change': 2.72,
  'changePercent': 1.01,
  'vwap': 271.985},
 {'symbol': 'AAPL',
  'date': '2026-04-17',
  'open': 266.96,
  'high': 272.3,
  'low': 266.72,
  'close': 270.23,
  'volume': 61436228,
  'change': 3.27,
  'changePercent': 1.22,
  'vwap': 269.0525},
 {'symbol': 'AAPL',
  'date': '2026-04-16',
  'open': 266.8,
  'high': 267.16,
  'low': 261.27,
  'close': 263.4,
  'volume': 43323112,
  'change': -3.4,
  'changePercent': -1.27,
  'vwap': 264.6575},
 {'symbol': 'AAPL',
  'date': '2026-04-15',
  'open': 258.16,
  'high': 266.56,
  'low': 257.81,
  'close': 266.43,
  'volume': 49913510,
  'change': 8.27,
  'changePercent': 3.2,
  'vwap': 262.24},
 {'symbol': 'AAPL',
  'date': '2026-04-14',
  'open': 259.25,
  'high': 261.93,
  'low': 257.19,
  'close': 258.83,
  'volume': 48370710,
  'change': -0.415,
  'changePercent': -0.16201,
  'vwap': 259.3},
 {'symbol': 'AAPL',
  'date': '2026-04-13',
  'open': 259.73,
  'high': 260.18,
  'low': 256.66,
  'close': 259.2,
  'volume': 36234700,
  'change': -0.53,
  'changePercent': -0.20406,
  'vwap': 258.9425},
 {'symbol': 'AAPL',
  'date': '2026-04-10',
  'open': 259.98,
  'high': 262.19,
  'low': 259.02,
  'close': 260.48,
  'volume': 31291500,
  'change': 0.5,
  'changePercent': 0.19232,
  'vwap': 260.4175},
 {'symbol': 'AAPL',
  'date': '2026-04-09',
  'open': 259,
  'high': 261.12,
  'low': 256.07,
  'close': 260.49,
  'volume': 28121600,
  'change': 1.49,
  'changePercent': 0.57529,
  'vwap': 259.17},
 {'symbol': 'AAPL',
  'date': '2026-04-08',
  'open': 258.45,
  'high': 259.75,
  'low': 256.53,
  'close': 258.9,
  'volume': 41032800,
  'change': 0.45,
  'changePercent': 0.17411,
  'vwap': 258.4075},
 {'symbol': 'AAPL',
  'date': '2026-04-07',
  'open': 256.15,
  'high': 256.2,
  'low': 245.7,
  'close': 253.5,
  'volume': 62148008,
  'change': -2.65,
  'changePercent': -1.03,
  'vwap': 252.8875},
 {'symbol': 'AAPL',
  'date': '2026-04-06',
  'open': 256.51,
  'high': 262.16,
  'low': 256.46,
  'close': 258.86,
  'volume': 29329911,
  'change': 2.35,
  'changePercent': 0.91614,
  'vwap': 258.4975},
 {'symbol': 'AAPL',
  'date': '2026-04-02',
  'open': 254.2,
  'high': 256.13,
  'low': 250.65,
  'close': 255.92,
  'volume': 31289400,
  'change': 1.72,
  'changePercent': 0.67663,
  'vwap': 254.225},
 {'symbol': 'AAPL',
  'date': '2026-04-01',
  'open': 254.08,
  'high': 256.18,
  'low': 253.33,
  'close': 255.63,
  'volume': 40059432,
  'change': 1.55,
  'changePercent': 0.61004,
  'vwap': 254.805},
 {'symbol': 'AAPL',
  'date': '2026-03-31',
  'open': 247.91,
  'high': 255.48,
  'low': 247.1,
  'close': 253.79,
  'volume': 49598100,
  'change': 5.88,
  'changePercent': 2.37,
  'vwap': 251.07},
 {'symbol': 'AAPL',
  'date': '2026-03-30',
  'open': 250.07,
  'high': 250.87,
  'low': 245.51,
  'close': 246.63,
  'volume': 39446213,
  'change': -3.44,
  'changePercent': -1.38,
  'vwap': 248.27},
 {'symbol': 'AAPL',
  'date': '2026-03-27',
  'open': 253.9,
  'high': 255.49,
  'low': 248.07,
  'close': 248.8,
  'volume': 47900000,
  'change': -5.1,
  'changePercent': -2.01,
  'vwap': 251.565},
 {'symbol': 'AAPL',
  'date': '2026-03-26',
  'open': 252.12,
  'high': 257,
  'low': 250.77,
  'close': 252.89,
  'volume': 41796700,
  'change': 0.775,
  'changePercent': 0.30541,
  'vwap': 253.195},
 {'symbol': 'AAPL',
  'date': '2026-03-25',
  'open': 254.1,
  'high': 255,
  'low': 251.6,
  'close': 252.62,
  'volume': 28476700,
  'change': -1.47,
  'changePercent': -0.58245,
  'vwap': 253.33},
 {'symbol': 'AAPL',
  'date': '2026-03-24',
  'open': 250.35,
  'high': 254.83,
  'low': 249.55,
  'close': 251.64,
  'volume': 45152300,
  'change': 1.29,
  'changePercent': 0.51528,
  'vwap': 251.5925},
 {'symbol': 'AAPL',
  'date': '2026-03-23',
  'open': 253.97,
  'high': 254.6,
  'low': 250.28,
  'close': 251.49,
  'volume': 40546109,
  'change': -2.48,
  'changePercent': -0.97649,
  'vwap': 252.585},
 {'symbol': 'AAPL',
  'date': '2026-03-20',
  'open': 247.98,
  'high': 249.2,
  'low': 246,
  'close': 247.99,
  'volume': 88331100,
  'change': 0.015,
  'changePercent': 0.00403258,
  'vwap': 247.7925},
 {'symbol': 'AAPL',
  'date': '2026-03-19',
  'open': 249.4,
  'high': 251.83,
  'low': 247.3,
  'close': 248.96,
  'volume': 34864100,
  'change': -0.44,
  'changePercent': -0.17642,
  'vwap': 249.3725},
 {'symbol': 'AAPL',
  'date': '2026-03-18',
  'open': 252.63,
  'high': 254.94,
  'low': 249,
  'close': 249.94,
  'volume': 35757900,
  'change': -2.69,
  'changePercent': -1.06,
  'vwap': 251.6275},
 {'symbol': 'AAPL',
  'date': '2026-03-17',
  'open': 252.96,
  'high': 255.13,
  'low': 252.18,
  'close': 254.23,
  'volume': 32361607,
  'change': 1.27,
  'changePercent': 0.50206,
  'vwap': 253.625},
 {'symbol': 'AAPL',
  'date': '2026-03-16',
  'open': 252.11,
  'high': 253.89,
  'low': 249.88,
  'close': 252.82,
  'volume': 32074209,
  'change': 0.715,
  'changePercent': 0.28162,
  'vwap': 252.175},
 {'symbol': 'AAPL',
  'date': '2026-03-13',
  'open': 255.48,
  'high': 256.33,
  'low': 249.52,
  'close': 250.12,
  'volume': 36930000,
  'change': -5.36,
  'changePercent': -2.1,
  'vwap': 252.8625},
 {'symbol': 'AAPL',
  'date': '2026-03-12',
  'open': 258.66,
  'high': 258.95,
  'low': 254.18,
  'close': 255.76,
  'volume': 40794020,
  'change': -2.9,
  'changePercent': -1.12,
  'vwap': 256.8875},
 {'symbol': 'AAPL',
  'date': '2026-03-11',
  'open': 261.09,
  'high': 262.13,
  'low': 259.55,
  'close': 260.81,
  'volume': 26218927,
  'change': -0.28,
  'changePercent': -0.10724,
  'vwap': 260.895},
 {'symbol': 'AAPL',
  'date': '2026-03-10',
  'open': 257.65,
  'high': 262.48,
  'low': 256.95,
  'close': 260.83,
  'volume': 30590800,
  'change': 3.19,
  'changePercent': 1.23,
  'vwap': 259.4775},
 {'symbol': 'AAPL',
  'date': '2026-03-09',
  'open': 255.69,
  'high': 261.15,
  'low': 253.68,
  'close': 259.88,
  'volume': 38218533,
  'change': 4.19,
  'changePercent': 1.64,
  'vwap': 257.6},
 {'symbol': 'AAPL',
  'date': '2026-03-06',
  'open': 258.63,
  'high': 258.77,
  'low': 254.37,
  'close': 257.46,
  'volume': 41120042,
  'change': -1.17,
  'changePercent': -0.45238,
  'vwap': 257.3075},
 {'symbol': 'AAPL',
  'date': '2026-03-05',
  'open': 260.79,
  'high': 261.56,
  'low': 257.25,
  'close': 260.29,
  'volume': 49658626,
  'change': -0.5,
  'changePercent': -0.19173,
  'vwap': 259.9725},
 {'symbol': 'AAPL',
  'date': '2026-03-04',
  'open': 264.65,
  'high': 266.15,
  'low': 261.42,
  'close': 262.52,
  'volume': 39803119,
  'change': -2.13,
  'changePercent': -0.80484,
  'vwap': 263.685},
 {'symbol': 'AAPL',
  'date': '2026-03-03',
  'open': 263.48,
  'high': 265.56,
  'low': 260.13,
  'close': 263.75,
  'volume': 38568921,
  'change': 0.27,
  'changePercent': 0.10247,
  'vwap': 263.23},
 {'symbol': 'AAPL',
  'date': '2026-03-02',
  'open': 262.41,
  'high': 266.53,
  'low': 260.2,
  'close': 264.72,
  'volume': 41827946,
  'change': 2.31,
  'changePercent': 0.8803,
  'vwap': 263.465},
 {'symbol': 'AAPL',
  'date': '2026-02-27',
  'open': 272.81,
  'high': 272.81,
  'low': 262.89,
  'close': 264.18,
  'volume': 72366505,
  'change': -8.63,
  'changePercent': -3.16,
  'vwap': 268.1725},
 {'symbol': 'AAPL',
  'date': '2026-02-26',
  'open': 274.95,
  'high': 276.11,
  'low': 270.8,
  'close': 272.95,
  'volume': 32345114,
  'change': -2,
  'changePercent': -0.7274,
  'vwap': 273.7025},
 {'symbol': 'AAPL',
  'date': '2026-02-25',
  'open': 271.78,
  'high': 274.94,
  'low': 271.05,
  'close': 274.23,
  'volume': 33714342,
  'change': 2.45,
  'changePercent': 0.90146,
  'vwap': 273},
 {'symbol': 'AAPL',
  'date': '2026-02-24',
  'open': 267.86,
  'high': 274.89,
  'low': 267.71,
  'close': 272.14,
  'volume': 47014619,
  'change': 4.28,
  'changePercent': 1.6,
  'vwap': 270.65},
 {'symbol': 'AAPL',
  'date': '2026-02-23',
  'open': 263.49,
  'high': 269.43,
  'low': 263.38,
  'close': 266.18,
  'volume': 37308200,
  'change': 2.69,
  'changePercent': 1.02,
  'vwap': 265.62},
 {'symbol': 'AAPL',
  'date': '2026-02-20',
  'open': 258.97,
  'high': 264.75,
  'low': 258.16,
  'close': 264.58,
  'volume': 42070500,
  'change': 5.61,
  'changePercent': 2.17,
  'vwap': 261.615},
 {'symbol': 'AAPL',
  'date': '2026-02-19',
  'open': 262.6,
  'high': 264.48,
  'low': 260.05,
  'close': 260.58,
  'volume': 30845300,
  'change': -2.02,
  'changePercent': -0.76923,
  'vwap': 261.9275},
 {'symbol': 'AAPL',
  'date': '2026-02-18',
  'open': 263.6,
  'high': 266.82,
  'low': 262.45,
  'close': 264.35,
  'volume': 34203337,
  'change': 0.75,
  'changePercent': 0.28452,
  'vwap': 264.305},
 {'symbol': 'AAPL',
  'date': '2026-02-17',
  'open': 258.05,
  'high': 266.29,
  'low': 255.54,
  'close': 263.88,
  'volume': 58469100,
  'change': 5.83,
  'changePercent': 2.26,
  'vwap': 260.94},
 {'symbol': 'AAPL',
  'date': '2026-02-13',
  'open': 262.01,
  'high': 262.23,
  'low': 255.45,
  'close': 255.78,
  'volume': 56290700,
  'change': -6.23,
  'changePercent': -2.38,
  'vwap': 258.8675},
 {'symbol': 'AAPL',
  'date': '2026-02-12',
  'open': 275.59,
  'high': 275.72,
  'low': 260.18,
  'close': 261.73,
  'volume': 81077229,
  'change': -13.86,
  'changePercent': -5.03,
  'vwap': 268.305},
 {'symbol': 'AAPL',
  'date': '2026-02-11',
  'open': 274.7,
  'high': 280.18,
  'low': 274.45,
  'close': 275.5,
  'volume': 51931300,
  'change': 0.805,
  'changePercent': 0.29123,
  'vwap': 276.2075},
 {'symbol': 'AAPL',
  'date': '2026-02-10',
  'open': 274.89,
  'high': 275.37,
  'low': 272.94,
  'close': 273.68,
  'volume': 34376900,
  'change': -1.2,
  'changePercent': -0.44018,
  'vwap': 274.22},
 {'symbol': 'AAPL',
  'date': '2026-02-09',
  'open': 277.9,
  'high': 278.2,
  'low': 271.7,
  'close': 274.62,
  'volume': 44623400,
  'change': -3.28,
  'changePercent': -1.18,
  'vwap': 275.605},
 {'symbol': 'AAPL',
  'date': '2026-02-06',
  'open': 277.12,
  'high': 280.9,
  'low': 276.93,
  'close': 278.12,
  'volume': 50453414,
  'change': 1,
  'changePercent': 0.36085,
  'vwap': 278.2675},
 {'symbol': 'AAPL',
  'date': '2026-02-05',
  'open': 278.13,
  'high': 279.5,
  'low': 273.23,
  'close': 275.91,
  'volume': 52977441,
  'change': -2.22,
  'changePercent': -0.79819,
  'vwap': 276.6925},
 {'symbol': 'AAPL',
  'date': '2026-02-04',
  'open': 272.29,
  'high': 278.95,
  'low': 272.29,
  'close': 276.49,
  'volume': 90545710,
  'change': 4.2,
  'changePercent': 1.54,
  'vwap': 275.005},
 {'symbol': 'AAPL',
  'date': '2026-02-03',
  'open': 269.2,
  'high': 271.88,
  'low': 267.61,
  'close': 269.48,
  'volume': 64394700,
  'change': 0.28,
  'changePercent': 0.10401,
  'vwap': 269.5425},
 {'symbol': 'AAPL',
  'date': '2026-02-02',
  'open': 260.03,
  'high': 270.49,
  'low': 259.21,
  'close': 270.01,
  'volume': 73913425,
  'change': 9.98,
  'changePercent': 3.84,
  'vwap': 264.935},
 {'symbol': 'AAPL',
  'date': '2026-01-30',
  'open': 255.17,
  'high': 261.9,
  'low': 252.18,
  'close': 259.48,
  'volume': 92443408,
  'change': 4.32,
  'changePercent': 1.69,
  'vwap': 257.1825},
 {'symbol': 'AAPL',
  'date': '2026-01-29',
  'open': 258,
  'high': 259.65,
  'low': 254.41,
  'close': 258.28,
  'volume': 67253009,
  'change': 0.28,
  'changePercent': 0.10853,
  'vwap': 257.585},
 {'symbol': 'AAPL',
  'date': '2026-01-28',
  'open': 257.65,
  'high': 258.86,
  'low': 254.51,
  'close': 256.44,
  'volume': 41288000,
  'change': -1.21,
  'changePercent': -0.46963,
  'vwap': 256.865},
 {'symbol': 'AAPL',
  'date': '2026-01-27',
  'open': 259.17,
  'high': 261.95,
  'low': 258.21,
  'close': 258.27,
  'volume': 49648300,
  'change': -0.9,
  'changePercent': -0.34726,
  'vwap': 259.4},
 {'symbol': 'AAPL',
  'date': '2026-01-26',
  'open': 251.48,
  'high': 256.56,
  'low': 249.8,
  'close': 255.41,
  'volume': 55969234,
  'change': 3.93,
  'changePercent': 1.56,
  'vwap': 253.3125},
 {'symbol': 'AAPL',
  'date': '2026-01-23',
  'open': 247.32,
  'high': 249.41,
  'low': 244.68,
  'close': 248.04,
  'volume': 41689000,
  'change': 0.72,
  'changePercent': 0.29112,
  'vwap': 247.3625},
 {'symbol': 'AAPL',
  'date': '2026-01-22',
  'open': 249.2,
  'high': 251,
  'low': 248.15,
  'close': 248.35,
  'volume': 39708340,
  'change': -0.85,
  'changePercent': -0.34109,
  'vwap': 249.175},
 {'symbol': 'AAPL',
  'date': '2026-01-21',
  'open': 248.7,
  'high': 251.56,
  'low': 245.18,
  'close': 247.65,
  'volume': 54641725,
  'change': -1.05,
  'changePercent': -0.4222,
  'vwap': 248.2725},
 {'symbol': 'AAPL',
  'date': '2026-01-20',
  'open': 252.73,
  'high': 254.79,
  'low': 243.42,
  'close': 246.7,
  'volume': 80267517,
  'change': -6.03,
  'changePercent': -2.39,
  'vwap': 249.41},
 {'symbol': 'AAPL',
  'date': '2026-01-16',
  'open': 257.9,
  'high': 258.9,
  'low': 254.93,
  'close': 255.53,
  'volume': 72142800,
  'change': -2.37,
  'changePercent': -0.91896,
  'vwap': 256.815},
 {'symbol': 'AAPL',
  'date': '2026-01-15',
  'open': 260.65,
  'high': 261.04,
  'low': 257.05,
  'close': 258.21,
  'volume': 39388600,
  'change': -2.44,
  'changePercent': -0.93612,
  'vwap': 259.2375},
 {'symbol': 'AAPL',
  'date': '2026-01-14',
  'open': 259.49,
  'high': 261.82,
  'low': 256.71,
  'close': 259.96,
  'volume': 40019421,
  'change': 0.47,
  'changePercent': 0.18112,
  'vwap': 259.495},
 {'symbol': 'AAPL',
  'date': '2026-01-13',
  'open': 258.72,
  'high': 261.81,
  'low': 258.39,
  'close': 261.05,
  'volume': 45730847,
  'change': 2.33,
  'changePercent': 0.90059,
  'vwap': 259.9925},
 {'symbol': 'AAPL',
  'date': '2026-01-12',
  'open': 259.16,
  'high': 261.3,
  'low': 256.8,
  'close': 260.25,
  'volume': 45263800,
  'change': 1.09,
  'changePercent': 0.42059,
  'vwap': 259.3775},
 {'symbol': 'AAPL',
  'date': '2026-01-09',
  'open': 259.08,
  'high': 260.21,
  'low': 256.22,
  'close': 259.37,
  'volume': 39997000,
  'change': 0.295,
  'changePercent': 0.11193,
  'vwap': 258.72},
 {'symbol': 'AAPL',
  'date': '2026-01-08',
  'open': 257.02,
  'high': 259.29,
  'low': 255.7,
  'close': 259.04,
  'volume': 50419337,
  'change': 2.02,
  'changePercent': 0.78593,
  'vwap': 257.7625},
 {'symbol': 'AAPL',
  'date': '2026-01-07',
  'open': 263.2,
  'high': 263.68,
  'low': 259.81,
  'close': 260.33,
  'volume': 48309804,
  'change': -2.87,
  'changePercent': -1.09,
  'vwap': 261.755},
 {'symbol': 'AAPL',
  'date': '2026-01-06',
  'open': 267,
  'high': 267.55,
  'low': 262.12,
  'close': 262.36,
  'volume': 52352100,
  'change': -4.64,
  'changePercent': -1.74,
  'vwap': 264.7575},
 {'symbol': 'AAPL',
  'date': '2026-01-05',
  'open': 270.64,
  'high': 271.51,
  'low': 266.14,
  'close': 267.26,
  'volume': 45647200,
  'change': -3.38,
  'changePercent': -1.25,
  'vwap': 268.8875},
 {'symbol': 'AAPL',
  'date': '2026-01-02',
  'open': 272.26,
  'high': 277.84,
  'low': 269,
  'close': 271.01,
  'volume': 37838100,
  'change': -1.25,
  'changePercent': -0.45912,
  'vwap': 272.5275},
 {'symbol': 'AAPL',
  'date': '2025-12-31',
  'open': 273.06,
  'high': 273.68,
  'low': 271.75,

In [5]:
df = pd.DataFrame(data)

df["date"] = pd.to_datetime(df["date"])
df = df.sort_values("date")

df.head()

,symbol,date,open,high,low,close,volume,change,changePercent,vwap
1254,AAPL,2021-05-25,127.82,128.32,126.32,126.90,72009500,-0.920,-0.719760,127.3400
1253,AAPL,2021-05-26,126.96,127.39,126.42,126.85,56575920,-0.105,-0.086641,126.9050
1252,AAPL,2021-05-27,126.44,127.64,125.08,125.28,94625601,-1.160,-0.917430,126.1100
1251,AAPL,2021-05-28,125.57,125.80,124.55,124.61,71311109,-0.960,-0.764510,125.1325
1250,AAPL,2021-06-01,125.08,125.35,123.94,124.28,67637118,-0.800,-0.639590,124.6625

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1255 entries, 1254 to 0
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   symbol         1255 non-null   str
 1   date           1255 non-null   datetime64[us]
 2   open           1255 non-null   float64
 3   high           1255 non-null   float64
 4   low            1255 non-null   float64
 5   close          1255 non-null   float64
 6   volume         1255 non-null   int64
 7   change         1255 non-null   float64
 8   changePercent  1255 non-null   float64
 9   vwap           1255 non-null   float64
dtypes: datetime64[us](1), float64(7), int64(1), str(1)
memory usage: 103.2 KB

In [13]:
from dotenv import load_dotenv
import os
import requests
import pandas as pd
from pathlib import Path

load_dotenv()

API_KEY = os.getenv("FMP_API_KEY")

if API_KEY is None:
    raise ValueError("No se encontró FMP_API_KEY en el archivo .env")

ticker = "AAPL"

url = "https://financialmodelingprep.com/stable/balance-sheet-statement"

params = {
    "symbol": ticker,
    "apikey": API_KEY
}

response = requests.get(url, params=params)

print("Status code:", response.status_code)
print("URL:", response.url.replace(API_KEY, "API_KEY_HIDDEN"))

data = response.json()

type(data), len(data)

Status code: 200
URL: https://financialmodelingprep.com/stable/balance-sheet-statement?symbol=AAPL&apikey=API_KEY_HIDDEN

(list, 5)

In [8]:
data

[{'date': '2025-09-27',
  'symbol': 'AAPL',
  'reportedCurrency': 'USD',
  'cik': '0000320193',
  'filingDate': '2025-10-31',
  'acceptedDate': '2025-10-31 06:01:26',
  'fiscalYear': '2025',
  'period': 'FY',
  'cashAndCashEquivalents': 35934000000,
  'shortTermInvestments': 18763000000,
  'cashAndShortTermInvestments': 54697000000,
  'netReceivables': 72957000000,
  'accountsReceivables': 39777000000,
  'otherReceivables': 33180000000,
  'inventory': 5718000000,
  'prepaids': 0,
  'otherCurrentAssets': 14585000000,
  'totalCurrentAssets': 147957000000,
  'propertyPlantEquipmentNet': 49834000000,
  'goodwill': 0,
  'intangibleAssets': 0,
  'goodwillAndIntangibleAssets': 0,
  'longTermInvestments': 77723000000,
  'taxAssets': 20777000000,
  'otherNonCurrentAssets': 62950000000,
  'totalNonCurrentAssets': 211284000000,
  'otherAssets': 0,
  'totalAssets': 359241000000,
  'totalPayables': 82876000000,
  'accountPayables': 69860000000,
  'otherPayables': 13016000000,
  'accruedExpenses': 8919000000,
  'shortTermDebt': 20329000000,
  'capitalLeaseObligationsCurrent': 2117000000,
  'taxPayables': 0,
  'deferredRevenue': 9055000000,
  'otherCurrentLiabilities': 42335000000,
  'totalCurrentLiabilities': 165631000000,
  'longTermDebt': 78328000000,
  'capitalLeaseObligationsNonCurrent': 11603000000,
  'deferredRevenueNonCurrent': 0,
  'deferredTaxLiabilitiesNonCurrent': 0,
  'otherNonCurrentLiabilities': 29946000000,
  'totalNonCurrentLiabilities': 119877000000,
  'otherLiabilities': 0,
  'capitalLeaseObligations': 13720000000,
  'totalLiabilities': 285508000000,
  'treasuryStock': 0,
  'preferredStock': 0,
  'commonStock': 93568000000,
  'retainedEarnings': -14264000000,
  'additionalPaidInCapital': 0,
  'accumulatedOtherComprehensiveIncomeLoss': -5571000000,
  'otherTotalStockholdersEquity': 0,
  'totalStockholdersEquity': 73733000000,
  'totalEquity': 73733000000,
  'minorityInterest': 0,
  'totalLiabilitiesAndTotalEquity': 359241000000,
  'totalInvestments': 96486000000,
  'totalDebt': 112377000000,
  'netDebt': 76443000000},
 {'date': '2024-09-28',
  'symbol': 'AAPL',
  'reportedCurrency': 'USD',
  'cik': '0000320193',
  'filingDate': '2024-11-01',
  'acceptedDate': '2024-11-01 06:01:36',
  'fiscalYear': '2024',
  'period': 'FY',
  'cashAndCashEquivalents': 29943000000,
  'shortTermInvestments': 35228000000,
  'cashAndShortTermInvestments': 65171000000,
  'netReceivables': 66243000000,
  'accountsReceivables': 33410000000,
  'otherReceivables': 32833000000,
  'inventory': 7286000000,
  'prepaids': 0,
  'otherCurrentAssets': 14287000000,
  'totalCurrentAssets': 152987000000,
  'propertyPlantEquipmentNet': 45680000000,
  'goodwill': 0,
  'intangibleAssets': 0,
  'goodwillAndIntangibleAssets': 0,
  'longTermInvestments': 91479000000,
  'taxAssets': 19499000000,
  'otherNonCurrentAssets': 55335000000,
  'totalNonCurrentAssets': 211993000000,
  'otherAssets': 0,
  'totalAssets': 364980000000,
  'totalPayables': 95561000000,
  'accountPayables': 68960000000,
  'otherPayables': 26601000000,
  'accruedExpenses': 0,
  'shortTermDebt': 20879000000,
  'capitalLeaseObligationsCurrent': 1632000000,
  'taxPayables': 26601000000,
  'deferredRevenue': 8249000000,
  'otherCurrentLiabilities': 50071000000,
  'totalCurrentLiabilities': 176392000000,
  'longTermDebt': 85750000000,
  'capitalLeaseObligationsNonCurrent': 10798000000,
  'deferredRevenueNonCurrent': 0,
  'deferredTaxLiabilitiesNonCurrent': 0,
  'otherNonCurrentLiabilities': 35090000000,
  'totalNonCurrentLiabilities': 131638000000,
  'otherLiabilities': 0,
  'capitalLeaseObligations': 12430000000,
  'totalLiabilities': 308030000000,
  'treasuryStock': 0,
  'preferredStock': 0,
  'commonStock': 83276000000,
  'retainedEarnings': -19154000000,
  'additionalPaidInCapital': 0,
  'accumulatedOtherComprehensiveIncomeLoss': -7172000000,
  'otherTotalStockholdersEquity': 0,
  'totalStockholdersEquity': 56950000000,
  'totalEquity': 56950000000,
  'minorityInterest': 0,
  'totalLiabilitiesAndTotalEquity': 364980000000,
  'totalInvestments': 126707000000,
  'totalDebt': 119059000000,
  'netDebt': 89116000000},
 {'date': '2023-09-30',
  'symbol': 'AAPL',
  'reportedCurrency': 'USD',
  'cik': '0000320193',
  'filingDate': '2023-11-03',
  'acceptedDate': '2023-11-02 18:08:27',
  'fiscalYear': '2023',
  'period': 'FY',
  'cashAndCashEquivalents': 29965000000,
  'shortTermInvestments': 31590000000,
  'cashAndShortTermInvestments': 61555000000,
  'netReceivables': 60985000000,
  'accountsReceivables': 29508000000,
  'otherReceivables': 31477000000,
  'inventory': 6331000000,
  'prepaids': 0,
  'otherCurrentAssets': 14695000000,
  'totalCurrentAssets': 143566000000,
  'propertyPlantEquipmentNet': 54376000000,
  'goodwill': 0,
  'intangibleAssets': 0,
  'goodwillAndIntangibleAssets': 0,
  'longTermInvestments': 100544000000,
  'taxAssets': 17852000000,
  'otherNonCurrentAssets': 36245000000,
  'totalNonCurrentAssets': 209017000000,
  'otherAssets': 0,
  'totalAssets': 352583000000,
  'totalPayables': 71430000000,
  'accountPayables': 62611000000,
  'otherPayables': 8819000000,
  'accruedExpenses': 0,
  'shortTermDebt': 15807000000,
  'capitalLeaseObligationsCurrent': 1575000000,
  'taxPayables': 8819000000,
  'deferredRevenue': 8061000000,
  'otherCurrentLiabilities': 48435000000,
  'totalCurrentLiabilities': 145308000000,
  'longTermDebt': 95281000000,
  'capitalLeaseObligationsNonCurrent': 11267000000,
  'deferredRevenueNonCurrent': 0,
  'deferredTaxLiabilitiesNonCurrent': 0,
  'otherNonCurrentLiabilities': 38581000000,
  'totalNonCurrentLiabilities': 145129000000,
  'otherLiabilities': 0,
  'capitalLeaseObligations': 12842000000,
  'totalLiabilities': 290437000000,
  'treasuryStock': 0,
  'preferredStock': 0,
  'commonStock': 73812000000,
  'retainedEarnings': -214000000,
  'additionalPaidInCapital': 0,
  'accumulatedOtherComprehensiveIncomeLoss': -11452000000,
  'otherTotalStockholdersEquity': 0,
  'totalStockholdersEquity': 62146000000,
  'totalEquity': 62146000000,
  'minorityInterest': 0,
  'totalLiabilitiesAndTotalEquity': 352583000000,
  'totalInvestments': 132134000000,
  'totalDebt': 123930000000,
  'netDebt': 93965000000},
 {'date': '2022-09-24',
  'symbol': 'AAPL',
  'reportedCurrency': 'USD',
  'cik': '0000320193',
  'filingDate': '2022-10-28',
  'acceptedDate': '2022-10-27 18:01:14',
  'fiscalYear': '2022',
  'period': 'FY',
  'cashAndCashEquivalents': 23646000000,
  'shortTermInvestments': 24658000000,
  'cashAndShortTermInvestments': 48304000000,
  'netReceivables': 60932000000,
  'accountsReceivables': 28184000000,
  'otherReceivables': 32748000000,
  'inventory': 4946000000,
  'prepaids': 0,
  'otherCurrentAssets': 21223000000,
  'totalCurrentAssets': 135405000000,
  'propertyPlantEquipmentNet': 52534000000,
  'goodwill': 0,
  'intangibleAssets': 0,
  'goodwillAndIntangibleAssets': 0,
  'longTermInvestments': 120805000000,
  'taxAssets': 15375000000,
  'otherNonCurrentAssets': 28636000000,
  'totalNonCurrentAssets': 217350000000,
  'otherAssets': 0,
  'totalAssets': 352755000000,
  'totalPayables': 70667000000,
  'accountPayables': 64115000000,
  'otherPayables': 6552000000,
  'accruedExpenses': 0,
  'shortTermDebt': 21110000000,
  'capitalLeaseObligationsCurrent': 1663000000,
  'taxPayables': 6552000000,
  'deferredRevenue': 7912000000,
  'otherCurrentLiabilities': 52630000000,
  'totalCurrentLiabilities': 153982000000,
  'longTermDebt': 98959000000,
  'capitalLeaseObligationsNonCurrent': 10748000000,
  'deferredRevenueNonCurrent': 0,
  'deferredTaxLiabilitiesNonCurrent': 0,
  'otherNonCurrentLiabilities': 38394000000,
  'totalNonCurrentLiabilities': 148101000000,
  'otherLiabilities': 0,
  'capitalLeaseObligations': 12411000000,
  'totalLiabilities': 302083000000,
  'treasuryStock': 0,
  'preferredStock': 0,
  'commonStock': 64849000000,
  'retainedEarnings': -3068000000,
  'additionalPaidInCapital': 0,
  'accumulatedOtherComprehensiveIncomeLoss': -11109000000,
  'otherTotalStockholdersEquity': 0,
  'totalStockholdersEquity': 50672000000,
  'totalEquity': 50672000000,
  'minorityInterest': 0,
  'totalLiabilitiesAndTotalEquity': 352755000000,
  'totalInvestments': 145463000000,
  'totalDebt': 132480000000,
  'netDebt': 108834000000},
 {'date': '2021-09-25',
  'symbol': 'AAPL',
  'reportedCurrency': 'USD',
  'cik': '0000320193',
  'filingDate': '2021-10-29',
  'acceptedDate': '2021-10-28 18:04:28',
  'fiscalYear': '2021',
  'period': 'FY',
  'cashAndCashEquivalents': 34940000000,
  'shortTermInvestments': 27699000000,
  'cashAndShortTermInvestments': 62639000000,
  'netReceivables': 51506000000,
  'accountsReceivables': 26278000000,
  'otherReceivables': 25228000000,
  'inventory': 6580000000,
  'prepaids': 0,
  'otherCurrentAssets': 14111000000,
  'totalCurrentAssets': 134836000000,
  'propertyPlantEquipmentNet': 49527000000,
  'goodwill': 0,
  'intangibleAssets': 0,
  'goodwillAndIntangibleAssets': 0,
  'longTermInvestments': 127877000000,
  'taxAssets': 0,
  'otherNonCurrentAssets': 38762000000,
  'totalNonCurrentAssets': 216166000000,
  'otherAssets': 0,
  'totalAssets': 351002000000,
  'totalPayables': 54763000000,
  'accountPayables': 54763000000,
  'otherPayables': 0,
  'accruedExpenses': 0,
  'shortTermDebt': 15613000000,
  'capitalLeaseObligationsCurrent': 1528000000,
  'taxPayables': 0,
  'deferredRevenue': 7612000000,
  'otherCurrentLiabilities': 45965000000,
  'totalCurrentLiabilities': 125481000000,
  'longTermDebt': 109106000000,
  'capitalLeaseObligationsNonCurrent': 10275000000,
  'deferredRevenueNonCurrent': 0,
  'deferredTaxLiabilitiesNonCurrent': 0,
  'otherNonCurrentLiabilities': 43050000000,
  'totalNonCurrentLiabilities': 162431000000,
  'otherLiabilities': 0,
  'capitalLeaseObligations': 11803000000,
  'totalLiabilities': 287912000000,
  'treasuryStock': 0,
  'preferredStock': 0,
  'commonStock': 57365000000,
  'retainedEarnings': 5562000000,
  'additionalPaidInCapital': 0,
  'accumulatedOtherComprehensiveIncomeLoss': 163000000,
  'otherTotalStockholdersEquity': 0,
  'totalStockholdersEquity': 63090000000,
  'totalEquity': 63090000000,
  'minorityInterest': 0,
  'totalLiabilitiesAndTotalEquity': 351002000000,
  'totalInvestments': 155576000000,
  'totalDebt': 136522000000,
  'netDebt': 101582000000}]

In [11]:
df_balance = pd.DataFrame(data)

df_balance

,date,symbol,reportedCurrency,cik,filingDate,acceptedDate,fiscalYear,period,cashAndCashEquivalents,shortTermInvestments,...,additionalPaidInCapital,accumulatedOtherComprehensiveIncomeLoss,otherTotalStockholdersEquity,totalStockholdersEquity,totalEquity,minorityInterest,totalLiabilitiesAndTotalEquity,totalInvestments,totalDebt,netDebt
0,2025-09-27,AAPL,USD,0000320193,2025-10-31,2025-10-31 06:01:26,2025,FY,35934000000,18763000000,...,0,-5571000000,0,73733000000,73733000000,0,359241000000,96486000000,112377000000,76443000000
1,2024-09-28,AAPL,USD,0000320193,2024-11-01,2024-11-01 06:01:36,2024,FY,29943000000,35228000000,...,0,-7172000000,0,56950000000,56950000000,0,364980000000,126707000000,119059000000,89116000000
2,2023-09-30,AAPL,USD,0000320193,2023-11-03,2023-11-02 18:08:27,2023,FY,29965000000,31590000000,...,0,-11452000000,0,62146000000,62146000000,0,352583000000,132134000000,123930000000,93965000000
3,2022-09-24,AAPL,USD,0000320193,2022-10-28,2022-10-27 18:01:14,2022,FY,23646000000,24658000000,...,0,-11109000000,0,50672000000,50672000000,0,352755000000,145463000000,132480000000,108834000000
4,2021-09-25,AAPL,USD,0000320193,2021-10-29,2021-10-28 18:04:28,2021,FY,34940000000,27699000000,...,0,163000000,0,63090000000,63090000000,0,351002000000,155576000000,136522000000,101582000000

In [27]:
import pandas as pd

tickers_df = pd.read_csv("../../data/external/tickers.csv")

tickers = tickers_df["ticker"].tolist()

tickers

['AAPL', 'MSFT', 'GOOGL', 'AMZN', 'META', 'NVDA', 'TSLA']

In [28]:
import yfinance as yf
from pathlib import Path

output_dir = Path("../../data/raw/stocks")
output_dir.mkdir(parents=True, exist_ok=True)

for ticker in tickers:

    print(f"Descargando {ticker}...")

    df = yf.download(
        ticker,
        start="2000-01-01",
        auto_adjust=False,
        progress=False
    )

    if df.empty:
        print(f"No se encontraron datos para {ticker}")
        continue

    # Limpiar columnas
    df = df.reset_index()

    df.columns = [
        col[0] if isinstance(col, tuple) else col
        for col in df.columns
    ]

    df = df.rename(columns={"index": "date"})

    df.columns = (
        pd.Index(df.columns)
        .str.lower()
        .str.replace(" ", "_")
    )

    # Agregar ticker
    df["ticker"] = ticker

    # Guardar parquet
    output_path = output_dir / f"{ticker.lower()}.parquet"

    df.to_parquet(output_path, index=False)

    print(f"Guardado: {output_path}")

Descargando AAPL...
Guardado: ..\..\data\raw\stocks\aapl.parquet
Descargando MSFT...
Guardado: ..\..\data\raw\stocks\msft.parquet
Descargando GOOGL...
Guardado: ..\..\data\raw\stocks\googl.parquet
Descargando AMZN...
Guardado: ..\..\data\raw\stocks\amzn.parquet
Descargando META...
Guardado: ..\..\data\raw\stocks\meta.parquet
Descargando NVDA...
Guardado: ..\..\data\raw\stocks\nvda.parquet
Descargando TSLA...
Guardado: ..\..\data\raw\stocks\tsla.parquet

In [29]:
import pandas as pd
from pathlib import Path

data_dir = Path("../../data/raw/stocks")

files = list(data_dir.glob("*.parquet"))

files

[WindowsPath('../../data/raw/stocks/aapl.parquet'),
 WindowsPath('../../data/raw/stocks/amzn.parquet'),
 WindowsPath('../../data/raw/stocks/googl.parquet'),
 WindowsPath('../../data/raw/stocks/meta.parquet'),
 WindowsPath('../../data/raw/stocks/msft.parquet'),
 WindowsPath('../../data/raw/stocks/nvda.parquet'),
 WindowsPath('../../data/raw/stocks/tsla.parquet')]

In [32]:
dfs = []

for file in files:

    df = pd.read_parquet(file)

    # Si no guardaste ticker antes
    if "ticker" not in df.columns:
        df["ticker"] = file.stem.upper()

    dfs.append(df)

master_df = pd.concat(dfs, ignore_index=True)

master_df.head(-10)

,date,adj_close,close,high,low,open,volume,ticker
0,2000-01-03,0.837724,0.999442,1.004464,0.907924,0.936384,535796800,AAPL
1,2000-01-04,0.767096,0.915179,0.987723,0.903460,0.966518,512377600,AAPL
2,2000-01-05,0.778321,0.928571,0.987165,0.919643,0.926339,778321600,AAPL
3,2000-01-06,0.710966,0.848214,0.955357,0.848214,0.947545,767972800,AAPL
4,2000-01-07,0.744644,0.888393,0.901786,0.852679,0.861607,460734400,AAPL
...,...,...,...,...,...,...,...,...
39531,2026-05-04,392.510010,392.510010,394.640015,384.799988,390.230011,48765100,TSLA
39532,2026-05-05,389.369995,389.369995,402.119995,389.000000,395.190002,47780600,TSLA
39533,2026-05-06,398.730011,398.730011,401.679993,384.019989,386.250000,53465400,TSLA
39534,2026-05-07,411.790009,411.790009,415.829987,402.119995,407.480011,64294200,TSLA
39535,2026-05-08,428.350006,428.350006,431.200012,416.390015,416.480011,65050000,TSLA

In [35]:
master_df.dtypes

date         datetime64[ms]
adj_close           float64
close               float64
high                float64
low                 float64
open                float64
volume                int64
ticker                  str
dtype: object

In [38]:
master_df = master_df[
    ["ticker"] + [col for col in master_df.columns if col != "ticker"]
]

In [39]:
master_df = master_df.sort_values(["ticker", "date"])
master_df.head(-10)

,ticker,date,adj_close,close,high,low,open,volume
0,AAPL,2000-01-03,0.837724,0.999442,1.004464,0.907924,0.936384,535796800
1,AAPL,2000-01-04,0.767096,0.915179,0.987723,0.903460,0.966518,512377600
2,AAPL,2000-01-05,0.778321,0.928571,0.987165,0.919643,0.926339,778321600
3,AAPL,2000-01-06,0.710966,0.848214,0.955357,0.848214,0.947545,767972800
4,AAPL,2000-01-07,0.744644,0.888393,0.901786,0.852679,0.861607,460734400
...,...,...,...,...,...,...,...,...
39531,TSLA,2026-05-04,392.510010,392.510010,394.640015,384.799988,390.230011,48765100
39532,TSLA,2026-05-05,389.369995,389.369995,402.119995,389.000000,395.190002,47780600
39533,TSLA,2026-05-06,398.730011,398.730011,401.679993,384.019989,386.250000,53465400
39534,TSLA,2026-05-07,411.790009,411.790009,415.829987,402.119995,407.480011,64294200
39535,TSLA,2026-05-08,428.350006,428.350006,431.200012,416.390015,416.480011,65050000

Inicio prueba historico APPLE

In [22]:
import yfinance as yf
import pandas as pd

ticker = "AAPL"

df = yf.download(
    ticker,
    start="2000-01-01",
    end="2026-05-24",
    auto_adjust=False
)

df = df.reset_index()

df.head()

[*********************100%***********************]  1 of 1 completed

Price       index Adj Close     Close      High       Low      Open     Volume
Ticker                 AAPL      AAPL      AAPL      AAPL      AAPL       AAPL
0      2000-01-03  0.837724  0.999442  1.004464  0.907924  0.936384  535796800
1      2000-01-04  0.767096  0.915179  0.987723  0.903460  0.966518  512377600
2      2000-01-05  0.778321  0.928571  0.987165  0.919643  0.926339  778321600
3      2000-01-06  0.710966  0.848214  0.955357  0.848214  0.947545  767972800
4      2000-01-07  0.744644  0.888393  0.901786  0.852679  0.861607  460734400

In [23]:
df.columns = [col[0] if isinstance(col, tuple) else col for col in df.columns]
df.columns = (
    pd.Index(df.columns)
    .str.lower()
    .str.replace(" ", "_")
)
df = df.rename(columns={"index": "date"})

In [24]:
from pathlib import Path

output_dir = Path("../../data/raw/stocks")
output_dir.mkdir(parents=True, exist_ok=True)

output_path = output_dir / "aapl.parquet"

df.to_parquet(output_path, index=False)

print(f"Archivo guardado en: {output_path}")

Archivo guardado en: ..\..\data\raw\stocks\aapl.parquet

In [26]:
import pandas as pd

df = pd.read_parquet("../../data/raw/stocks/aapl.parquet")

df.head(-5)

,date,adj_close,close,high,low,open,volume
0,2000-01-03,0.837724,0.999442,1.004464,0.907924,0.936384,535796800
1,2000-01-04,0.767096,0.915179,0.987723,0.903460,0.966518,512377600
2,2000-01-05,0.778321,0.928571,0.987165,0.919643,0.926339,778321600
3,2000-01-06,0.710966,0.848214,0.955357,0.848214,0.947545,767972800
4,2000-01-07,0.744644,0.888393,0.901786,0.852679,0.861607,460734400
...,...,...,...,...,...,...,...
6627,2026-05-11,292.679993,292.679993,293.880005,290.230011,291.980011,42247300
6628,2026-05-12,294.799988,294.799988,295.269989,292.559998,292.559998,45748100
6629,2026-05-13,298.869995,298.869995,300.920013,293.500000,293.500000,52684300
6630,2026-05-14,298.209991,298.209991,300.450012,295.380005,299.820007,35324900
6631,2026-05-15,300.230011,300.230011,303.200012,296.519989,297.899994,54862800

Fin prueba historico APPLE